In [1]:
# # marks = [58,70,30,45,75]
# # updated_marks = []
# # for mark in marks:
# #     updated_marks.append(mark+5)
# # print("Marks:", marks)
# # print("Updated Marks:", updated_marks)


# import numpy as np
# marks = np.array([58,70,30,45,75])
# marks=marks+5
# print("Marks:", marks)
# print("Updated Marks:", updated_marks)

In [2]:
import numpy as np
marks = np.array([58,70,30,45,75])
marks+5

array([63, 75, 35, 50, 80])

In [3]:
!pip install numpy

In [15]:
import numpy as np

mark = np.array([88, 75, 66, 99])

mark = mark + 5

print(mark)


[ 93  80  71 104]


In [16]:
marks>45

array([ True,  True, False, False,  True])

In [17]:
marks=marks-5
marks/2
print(marks)

[48 60 20 35 65]


In [18]:
marks/2

array([24. , 30. , 10. , 17.5, 32.5])

In [19]:
marks>=45

array([ True,  True, False, False,  True])

In [23]:
marks[0]

np.int64(48)

Indexing

In [ ]:
print((variable) marks: ndarray[_AnyShape,_dtype])
print(marks)

In [24]:
print(marks[0])
print(marks[3])
print(marks[-1])

48
35
65


Traversing

In [25]:
for i in range(4):
    print(marks[i])

48
60
20
35


Slicing

In [21]:
marks[:2] # Academic teams want first 2 marks
marks[1:4]

array([60, 20, 35])

2D Arrays

In [27]:
marks=np.array([
    [85,78,90],
    [92,85,98],
    [76,82,80]]
)
# Rows -> students 
# columns -> subjects

In [28]:
print(marks)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [29]:
marks[0,1]

np.int64(78)

In [32]:
marks[0:2] # array[start:stop-1]

array([[85, 78, 90],
       [92, 85, 98]])

Slicing & Indexing

In [ ]:
marks[0][0] # array[start:stop-1] ->slicing
marks[0:2,0:2] # array[row,column] -> indexing

array([[85, 78, 90],
       [92, 85, 98]])

In [41]:
marks[2,1]


np.int64(82)

In [42]:
marks[0][2]

np.int64(90)

In [43]:
marks[1:,0]

array([92, 76])

In [44]:
marks[0][0]
marks[0:2][0:2]

array([[85, 78, 90],
       [92, 85, 98]])

In [ ]:
print(marks[1:,0])
# [92 76]
print(marks[1:][0])

# marks[1:]
#[92 85 98]
#[76 82 80]]

# marks[1:][0]
# [92 85 98]

[92 76]
[92 85 98]


In [46]:
marks[0][0:2]

array([85, 78])

In [54]:
b1=np.array([56,78,89])
b2=np.array([65,76,98])

comb=np.concatenate((b1,b2),axis=0)
comb

array([56, 78, 89, 65, 76, 98])

In [56]:
b1=np.array([
    [56,78,89],
    [34,45,67]]
    )
b2=np.array([
    [65,76,98],
    [89,98,78]]
    )

comb=np.concatenate((b1,b2),axis=1)
# array([[56,78,89,65,76,98],
#      [34,45,67,89,98,78]])
print("--------------------------")
comb0=np.concatenate((b1,b2),axis=0)
comb0

--------------------------


array([[56, 78, 89],
       [34, 45, 67],
       [65, 76, 98],
       [89, 98, 78]])

A combined dataset contains six students. The academic team wants to divide the data into two groups for separate processing.

''Split -> Always in an equal division
join -> combine

In [51]:
print(np.split(comb,2))

[array([56, 78, 89]), array([65, 76, 98])]


In [53]:
print(np.split(comb,2))

for array in np.split(comb,2):
    print(array)

[array([56, 78, 89]), array([65, 76, 98])]
[56 78 89]
[65 76 98]


Find where the mark is 78

Search

Conditional-based searching

In [57]:
np.where(marks==78)

(array([0]), array([1]))

In [64]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])

print(np.where(mark==78))
print(mark)

(array([0]), array([1]))
[[85 78 90]
 [92 85 98]
 [76 82 80]]


Positions

In [67]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])

np.where(mark>=80) # gives me indices
print(mark)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [ ]:
mark=np.array([[85,78,90],
      [92,85,98],
      [76,82,80]])

print(mark[np.where(mark>=80)]) # ---> gives exact values
print(mark)

[85 90 92 85 98 82 80]
[[85 78 90]
 [92 85 98]
 [76 82 80]]


Asec

In [68]:
np.sort(marks)

array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

Printing in  a reverse order (row wise sorting)

In [69]:
np.sort(marks)[::-1]

array([[76, 80, 82],
       [85, 92, 98],
       [78, 85, 90]])

column wise sorting

In [72]:
print(mark)

[[85 78 90]
 [92 85 98]
 [76 82 80]]


sort and reverse of whole array

In [ ]:
np.sort(mark,axis=1)  # column wise sort

array([[78, 85, 90],
       [85, 92, 98],
       [76, 80, 82]])

In [ ]:
np.sort(mark,axis=0)  # row wise sort

array([[76, 78, 80],
       [85, 82, 90],
       [92, 85, 98]])